---
- name: Our first play
  hosts: planetexpress

  tasks:
          - name: Install steam locomotive on CentOS machines
            become: yes
            yum:
                    name: sl
                    state: present
            when: ansible_distribution == "CentOS"

          - name: Install steam locomotive on Ubuntu machines
            become: yes
            apt:
                    name: sl
                    state: present
            when: ansible_distribution == "Ubuntu"
