---
- name: learning to recall var data
  hosts: localhost
  connection: local

  vars:
          telcom:
                  - ericsson
                  - alu
                  - avaya
                  - cisco
          heroes:
                  marvel:
                          - spiderman
                          - ironman
                          - daredevil
                  dc:
                          - wonderwoman
                          - batman
                          - superman

  tasks:
          - name: print out spiderman
            debug:
                    msg: "{{ heroes.marvel[0] }}"

          - name: print out batman
            debug:
                    msg: "{{ heroes.dc[1] }}"

          - name: print out ALL DC heroes
            debug:
                    msg: "{{ heroes.dc }}"

          - name: print out all dc heroes with a loop
            debug:
                    msg: "{{ item }}"
            loop: "{{ heroes.dc }}"          

          - name: print out cisco
            debug:
                    msg: "{{ telcom[3] }}"

          - name: print out ALL dc AND marvel heroes
            debug:
                    msg: "{{ item }}"
            loop: "{{ heroes.marvel + heroes.dc }}"
