---
- name: Install sl with yum
  hosts: planetexpress

  tasks:
          - name: Install steam locomotive with ym
            become: yes
            yum:
                    name: sl
                    state: present
