---
- name: bootsrapping and new user creation
  hosts: raiders
  gather_facts: no
  
  vars_files:
          - vars/indyusers.yml
  
  tasks:
          - name: update apt with latest repo info
            raw: "apt upgrade -y"
            become: yes
          
          - name: install py3 and pip3 with ansible raw
            raw: "apt install -y python3-pip"
            become: yes
          
          - name: create new group
            group:
                name: indymovies
                state: present
            become: yes
          
          - name: add newuser1 to target hosts
            user:
                    name: "{{ item }}"
                    state: present
                    group: indymovies
            become: yes
            loop: "{{ newusers }}"
